### ISSUE TITLE
If you ask baker for the events for a given process id. We would like to get the timestamp for the events

### ISSUE THREAD

**Issue by edwarddegraaf** [ing-bank/baker#100]
Hi,

You can ask baker to give the events for a given process Id. 

Is it possible to make it so that baker will supply the timestamps of these events?

regards

edward

**Comment by merlijn** [comment]
This is now supported in the [scala API](https://github.com/ing-bank/baker/blob/8dcfffad7c6803290445d537c02425453e88cbd6/runtime/src/main/scala/com/ing/baker/runtime/core/Baker.scala#L301)

For the java api it is somewhat more difficult since we have a ``EventList`` class that is difficult to add this feature to without breaking backwards compatibility.

**Comment by Tim-Linschoten** [comment]
Now added to Baker V3 branch
