### ISSUE TITLE
Support interfaces as ingredients in interactions

### ISSUE THREAD

**Issue by jdin** [ing-bank/baker#139]
At the moment it is not possible to have an interface as an ingredient in interaction with different implementations. It is quite a limitation.

**Comment by merlijn** [comment]
The underlying feature is to support an `Either` sort of type. 

**Step 1**  is to implement this in the baker type system. Which in java naturally maps to an interace with multiple implementing classes.

We should be able to to this in a backwards compatible way by generalizing the existing `EnumType` (which only supports strings) into an `EitherType` and `SingletonType`.

**Step 2** is how to know all possible implementation classes of an interface

Since there is no sealed trait in java, we need some hint of where to look.

Either a package name and use https://github.com/ronmamo/reflections

Or, require an annotation that lists all possibilities like:

```
@ImplementedBy(MyIngredientA.class, MyIngredientB.class)
interface MyIngredient {

}
```

**Comment by jdin** [comment]
Hi @nikolakasev. We just faced this problem with the following use case. 

We have an interaction where ingredient "payload" depends on other ingredient "requestType". Payload is very different per requestType. And we have 9 requestTypes and so 9 payloads. First our thought was to have an interface and different implementations. But this is not supported.

One of the other solutions is to use just a Map. But we do not really want it as you cannot force the types in this case and it is very difficult to use it later without documentation as you have to know which entries do you need to fill per requestType.

We have found a better solution for now. We create a class with all the fields there for all payloads (all requestTypes) and different builders per payload/requestType. It is a bit more work as you cannot use lombok here and you have to build those builders manually, but it should be nice to use later.

**Comment by nikolakasev** [comment]
What are the types of requests and payloads? 

Have you considered the granularity of your interaction? Maybe it's doing too much and splitting in separate interactions is an option?

Does the interaction require all the data from the "payload" ingredient or just a small part of it?

**Comment by jdin** [comment]
The interaction need to check that all the required fields for a specific requestType are filled in correctly and send this payload to a service. 
Splitting it is not a good option as you would have 9 interactions that do the same thing.
That is why we have decided to build different builders for the payload per requestType.
