### ISSUE TITLE
Baker should not add static field as Ingredients

### ISSUE THREAD

**Issue by pascal-warnimont** [ing-bank/baker#78]
Example : 

    public static final String REQUIRED_SIGNATURES = "requiredSignatures";
    private final SignatureList requiredSignatures;

Constant is reused  to lookup Ingredients in API (possibly not consistent with baker philosophy :), but since the result returned by the API varies with different events being present, there is already a dependency)

**Comment by merlijn** [comment]
Thank you for reporting! This is indeed a bug :(

It has been fixed in the 1.2.x release, 1.2.1 has been released today.

If this is urgent for you we back port the fix to 1.1.x. 

Alternatively you can move the static field to a different class for now. Please comment if this is OK for you, then I will close the issue.

**Comment by pascal-warnimont** [comment]
good it was fixed :)
